-- schema.sql
-- ZTDPP Device Registry Schema

CREATE TABLE IF NOT EXISTS devices (
    device_id TEXT PRIMARY KEY,
    public_key TEXT NOT NULL,
    registered_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    trusted INTEGER DEFAULT 1
);

-- Seed INSERT for device CAM-001
-- Real ECDSA P-256 public key generated by signer/keygen.py
INSERT OR IGNORE INTO devices (device_id, public_key, trusted) 
VALUES (
    'CAM-001', 
    '-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAELOn/8lKYRsGT7mAEtYXftVPXKIQ4
6GG7PWaFi+MzPWNecQ5Xdy0NkSGzMiOzhL/CfrQ2/VLoc+/nkgGb9QImDg==
-----END PUBLIC KEY-----', 
    1
);
